const routes = {
  adminPitch: "/adminPitch",
  comment: '/admin/comment',
  paymentAdmin: '/admin/payment',
  bookingAdmin: '/admin/booking',
  checkout: '/checkout',
  home: '/',
  register: '/register',
  login: '/login',
  verify: '/verify',
  admin: '/admin',
  post: '/admin/post',
  postAdd: '/admin/post/add',
  banner: '/admin/banner',
  service: '/admin/service',
  pitch: '/admin/pitch',
  location: '/admin/location',
  payment: '/admin/payment',
  booking: '/admin/booking',
  pitch_client: '/pitch',
  pitch_detail: '/pitch/detail/:id',
  bookingHistory: '/booking/history',
  about: '/about',
  contact: '/contact',
  childrenpitch: '/admin/childrenpitch',
  shift: '/admin/shift',
  childrenPitch_client: '/pitch/childrenPitch',
  post_client: '/post',
  post_detail: '/post/:id',
  find_opponent: '/pitch/find_opponent',
  admin_pitch: '/admin-pitch',
  notfound: '/notfound',
  service_admin: '/admin-pitch/service',
  pitch_admin: '/admin-pitch/pitch',
  location_admin: '/admin-pitch/location',
  payment_admin: '/admin-pitch/payment',
  booking_admin: '/admin-pitch/booking',
  childrenpitch_admin: '/admin-pitch/childrenpitch',
  shift_admin: '/admin-pitch/shift',
  user_admin: '/admin/user'
};

export { routes };
