const routes = {
  home: "/",
  about:"/about",
  contact:"/contact",
  register: "/register",
  login: "/login",
  verify: "/verify",
  admin: "/admin",
  post: "/admin/post",
  postAdd: "/admin/post/add",
  banner: "/admin/banner",
  service: "/admin/service",
  comment: "/admin/comment",
  pitch: "/admin/pitch",
  childrenpitch: "/admin/childrenpitch",
  shift: "/admin/shift",
  childrenPitch_client: "/pitch/childrenPitch",
  location: "/admin/location",
  payment: "/admin/payment",
  booking: "/admin/booking",
  pitch_client: "/pitch",
  pitch_detail: "/pitch/detail",
  post_client: "/post",
  post_detail: "/post/:id",
};

export { routes };
